[project]
name = "ai-for-engineering-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pip>=25.0.1",
    "ruff>=0.11.5",
]
