from pydantic import BaseModel, Field


class UserQueryForAgent(BaseModel):
    query: str = Field(
        ...,
        description="The user query to be processed by the agent.",
        examples=["What are some good movies about AI?"],
    )


class AgentResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The response generated by the agent.",
        examples=["Here are some movies about AI: Ex Machina, Her, The Matrix."],
    )
